# Generated by Django 3.2.8 on 2021-10-30 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('feeling', multiselectfield.db.fields.MultiSelectField(choices=[('antusias', 'Antusias'), ('gembira', 'Gembira'), ('takjub', 'Takjub'), ('semangat', 'Semangat'), ('bangga', 'Bangga'), ('penuh_cinta', 'Penuh Cinta'), ('santai', 'Santai'), ('tenang', 'Tenang'), ('puas', 'Puas'), ('lega', 'Lega'), ('marah', 'Marah'), ('takut', 'Takut'), ('stres', 'Stres'), ('waspada', 'Waspada'), ('kewalahan', 'Kewalahan'), ('kesal', 'Kesal'), ('malu', 'Malu'), ('cemas', 'Cemas'), ('lesu', 'Lesu'), ('sedih', 'Sedih'), ('duka', 'Duka'), ('bosan', 'Bosan'), ('kesepian', 'Kesepian'), ('bingung', 'Bingung')], max_length=167)),
                ('factor', multiselectfield.db.fields.MultiSelectField(choices=[('keluarga', 'Keluarga'), ('pekerjaan', 'Pekerjaan'), ('teman', 'Teman'), ('percintaan', 'Percintaan'), ('kesehatan', 'Kesehatan'), ('pendidikan', 'Pendidikan'), ('tidur', 'Tidur'), ('perjalanan', 'Perjalanan'), ('bersantai', 'Bersantai'), ('makanan', 'Makanan'), ('olahraga', 'Olahraga'), ('seni', 'Seni'), ('hobi', 'Hobi'), ('cuaca', 'Cuaca'), ('belanja', 'Belanja'), ('hiburan', 'Hiburan'), ('keuangan', 'Keuangan'), ('ibadah', 'Ibadah'), ('refleksi_diri', 'Refleksi Diri')], max_length=162)),
                ('anxiety_rate', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
