# Generated by Django 3.2.8 on 2021-10-27 03:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_anxiety_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='factor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('keluarga', 'Keluarga'), ('pekerjaan', 'Pekerjaan'), ('teman', 'Teman'), ('percintaan', 'Percintaan'), ('kesehatan', 'Kesehatan'), ('pendidikan', 'Pendidikan'), ('tidur', 'Tidur'), ('perjalanan', 'Perjalanan'), ('bersantai', 'Bersantai'), ('makanan', 'Makanan'), ('olahraga', 'Olahraga'), ('seni', 'Seni'), ('hobi', 'Hobi'), ('cuaca', 'Cuaca'), ('belanja', 'Belanja'), ('hiburan', 'Hiburan'), ('keuangan', 'Keuangan'), ('ibadah', 'Ibadah'), ('refleksi_diri', 'Refleksi Diri')], max_length=162, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='anxiety_rate',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='feeling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('antusias', 'Antusias'), ('gembira', 'Gembira'), ('takjub', 'Takjub'), ('semangat', 'Semangat'), ('bangga', 'Bangga'), ('penuh_cinta', 'Penuh Cinta'), ('santai', 'Santai'), ('tenang', 'Tenang'), ('puas', 'Puas'), ('lega', 'Lega'), ('marah', 'Marah'), ('takut', 'Takut'), ('stres', 'Stres'), ('waspada', 'Waspada'), ('kewalahan', 'Kewalahan'), ('kesal', 'Kesal'), ('malu', 'Malu'), ('cemas', 'Cemas'), ('lesu', 'Lesu'), ('sedih', 'Sedih'), ('duka', 'Duka'), ('bosan', 'Bosan'), ('kesepian', 'Kesepian'), ('bingung', 'Bingung')], max_length=167),
        ),
    ]
