# Generated by Django 3.2.8 on 2021-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutipan_penyemangat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quotes_form',
            field=models.CharField(max_length=2000),
        ),
    ]
