# Generated by Django 3.2.7 on 2021-10-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutipan_penyemangat', '0003_auto_20211027_1842'),
        ('kutipan_penyemangat', '0003_auto_20211028_1323'),
    ]

    operations = [
    ]
