# Generated by Django 3.2.8 on 2021-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='query_topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Query Topic'),
        ),
    ]
