# Generated by Django 3.2.8 on 2021-10-31 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tembok_harapan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harapan',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='harapan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
